---
- name: Enable firewall
  systemd:
    name: firewalld
    state: started
    enabled: true
  tags:
    - configure

- name: Configure firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
  tags:
    - configure