---
- name: Install epel-release
  yum:
    name: epel-release
    state: present
  tags:
    - install

- name: Install NGINX
  yum:
    name: nginx
    state: present
  notify:
    - enable nginx
    - start nginx
  tags:
    - install

- import_tasks: firewall.yaml