---
- name: Install python-mysql
  yum:
    name: MySQL-python
    state: present
  tags:
    - install

- name: Install mariadb repo
  template:
    src: MariaDB.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
  tags:
    - install

- name: Install mariadb server and client
  yum:
    name:
      - MariaDB-server
      - MariaDB-client
    state: present
  notify:
    - enable mariadb
    - start mariadb
  tags:
    - install

- name: Flush pending handlers
  meta: flush_handlers

- name: Sets the root password
  mysql_user:
    user: root
    password: "password"
    host: localhost
    login_password: "cobak"
  tags:
    - never
    - ubah-password

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user:
    user: ""
    host: "{{ ansible_fqdn }}"
    state: "absent"
  tags:
    - configure

- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: "absent"
  tags:
    - configure

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "::1"
  tags:
    - configure

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "127.0.0.1"
  tags:
    - configure

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "localhost"
  tags:
    - configure

- name: Secures the MySQL root user for server_hostname domain
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "{{ ansible_fqdn }}"
  tags:
    - configure

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
  tags:
    - configure