---
- name: enable php-fpm
  systemd:
    name: php-fpm
    enabled: true

- name: start php-fpm
  systemd:
    name: php-fpm
    state: started

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted